name: release & pages
on:
  release:
    branches: [master]
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: generate static vuepress files
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: install dependencies
        run: |
          npm ci
          npm run build

      - name: generate docs
        run: |
          cd docs/
          npm install
          npm run build

      - name: init new repo in dist folder and commit generated files
        run: |
          cd docs/src/.vuepress/dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
          echo "RELEASE_TARGET_BRANCH: $RELEASE_TARGET_BRANCH"
          npm --no-git-tag-version version $RELEASE_TAG_NAME
        env:
          RELEASE_TARGET_BRANCH: ${{ github.event.release.tag_name }}

      - name: force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/src/.vuepress/dist

      - name: release
        if: "$RELEASE_TARGET_BRANCH == 'next'"
        run: |
          echo "RELEASE_TARGET_BRANCH: $RELEASE_TARGET_BRANCH"
          npm publish --tag $RELEASE_TARGET_BRANCH
        run: |
          echo "RELEASE_TARGET_BRANCH: $RELEASE_TARGET_BRANCH"
          npm publish $RELEASE_TARGET_BRANCH
        env:
          RELEASE_TARGET_BRANCH: ${{ github.event.release.target_commitish }}
